#!/usr/bin/with-contenv bash
. "/usr/local/bin/util"

info "Starting read_decrypt"

if [[ -z "$(ls -A ${read_decrypt_dir})" ]]; then
    info "Mounting read_decrypt Google Drive: ${read_decrypt_dir}"
    exec rclone mount ${read_decrypt_mount_options} "${read_decrypt_endpoint}" "${read_decrypt_dir}" &
    PID=${!}
    sleep 1
    fdmove -c 2 1 fdmove 1 3 echo >> /dev/null fdmove -c 1 2
    wait ${PID}
else
    error "Google Drive read_decrypt mountpoint: ${read_decrypt_dir} already mounted."
fi

exit $?
