#!/usr/bin/with-contenv bash
. "/usr/local/bin/util"
/bin/s6-svwait -U /var/run/s6/services/read_decrypt >/dev/null 2>&1
/bin/s6-svwait -U /var/run/s6/services/cloud_decrypt >/dev/null 2>&1

info "Starting local_media"

if [[ $(mergerfs_pid | wc -l) == "0" ]]; then
    mfs_mounts="${local_decrypt_dir}:${read_decrypt_dir}:${cloud_decrypt_dir}"
    info "Mounting local_media: ${local_media_dir}"
    mergerfs ${mfs_options} "${mfs_mounts}" "${local_media_dir}"
    while [[ $(mergerfs_pid | wc -l) == "0" ]]
    do
        warn "Waiting for mount ${local_media_dir} ..."
        sleep 2
    done
    PID=$(mergerfs_pid)
    sleep 1
    fdmove -c 2 1 fdmove 1 3 echo >> /dev/null fdmove -c 1 2
    while [[ -e /proc/${PID} ]]
    do
        sleep 0.1
    done
else
    error "local_media mountpoint: ${local_media_dir} already mounted."
fi

exit 0
