#!/usr/bin/with-contenv bash
. "/usr/local/bin/util"
/bin/s6-svwait -U /var/run/s6/services/read_decrypt
/bin/s6-svwait -U /var/run/s6/services/cloud_decrypt

info "Starting local_media"

term_handler() {
    info "local_media SIGTERM received"
    unmount
    info "local_media sending SIGTERM to child pid"
    s6-svc -t /var/run/s6/services/cloud_decrypt
    s6-svc -t /var/run/s6/services/read_decrypt
    kill -SIGTERM ${PID} >/dev/null 2>&1
    info "local_media exiting"
    exit 0
}

quit_handler() {
    info "local_media SIGQUIT received"
    unmount
    info "local_media sending SIGTERM to child pid"
    kill -SIGTERM ${PID} >/dev/null 2>&1
    info "local_media exiting"
    exit 0
}

unmount() {
    info "local_media unmounting ${local_media_dir}"
    rclone_unmount ${local_media_dir}
}

trap term_handler SIGTERM
trap quit_handler SIGQUIT

if [[ $(mergerfs_pid | wc -l) == "0" ]]; then
    mfs_mounts="${local_decrypt_dir}:${read_decrypt_dir}:${cloud_decrypt_dir}"
    info "Mounting local_media: ${local_media_dir}"
    mergerfs ${mfs_options} "${mfs_mounts}" "${local_media_dir}"
    while [[ $(mergerfs_pid | wc -l) == "0" ]]
    do
        warn "Waiting for mount ${local_media_dir} ..."
        sleep 2
    done
    PID=$(mergerfs_pid)
    sleep 1
    fdmove -c 2 1 fdmove 1 3 echo >> /dev/null fdmove -c 1 2
    while [[ -e /proc/${PID} ]]
    do
        sleep 0.1
    done
else
    error "local_media mountpoint: ${local_media_dir} already mounted."
fi

error "local_media script error"
unmount
s6-svc -t /var/run/s6/services/cloud_decrypt
s6-svc -t /var/run/s6/services/read_decrypt
info "local_media exiting"
exit 1
