#!/bin/bash
. "config"

all_good=1

check_rclone_read
check_rclone_cloud

if [[ $(ps -ef | grep "rclone" | grep -v "grep" | wc -l) == "0" ]]; then
  log "ERROR" "rclone is not running"
  all_good=0
fi

if [[ -z "$(ls -A ${cloud_decrypt_dir})" ]]; then
  log "ERROR" "Waiting for ${cloud_decrypt_dir}"
  exit 0
fi

if [[ -z "$(ls -A ${read_decrypt_dir})" ]]; then
  log "ERROR" "Waiting for ${read_decrypt_dir}"
  exit 0
fi

if [[ $(ps -ef | grep "mergerfs" | grep -v "grep" | wc -l) == "0" ]]; then
  log "ERROR" "MergerFS is not running"
  all_good=0
fi

if [[ "$all_good" -eq "1" ]]; then
  log "DEBUG" "All checks succeeded"
fi
