#!/bin/bash
. "variables"

check_rclone_read () {
	if [[ ! "${rclone_read_endpoint}" == *: ]]; then
		printf "\n\n"
		echo "Missing colon (:) in RCLONE_READ_ENDPOINT (${rclone_read_endpoint})"
		echo "Run: docker exec -ti <DOCKER_CONTAINER> rclone_setup"
		printf "\n\n"
    sleep 5000
		exit 02
	fi

	if [[ "$(rclone listremotes ${rclone_config} | grep "${rclone_read_endpoint}" | wc -l)" == "0" ]]; then
		printf "\n\n"
		echo "RCLONE_READ_ENDPOINT (${rclone_read_endpoint}) endpoint has not been created within rclone"
		echo "Run: docker exec -ti <DOCKER_CONTAINER> rclone_setup"
		printf "\n\n"
    sleep 5000
		exit 02
	fi
}

check_rclone_cloud () {
	if [[ ! "${rclone_cloud_endpoint}" == *: ]]; then
		printf "\n\n"
		echo "Missing colon (:) in RCLONE_CLOUD_ENDPOINT (${rclone_cloud_endpoint})"
		echo "Run: docker exec -ti <DOCKER_CONTAINER> rclone_setup"
		printf "\n\n"
    sleep 5000
		exit 02
	fi

	if [ "$(rclone listremotes $rclone_config | grep "${rclone_cloud_endpoint}" | wc -l)" == "0" ]; then
		printf "\n\n"
		echo "RCLONE_CLOUD_ENDPOINT (${rclone_cloud_endpoint}) endpoint has not been created within rclone"
		echo "Run: docker exec -ti <DOCKER_CONTAINER> rclone_setup"
		printf "\n\n"
    sleep 5000
		exit 02
	fi
}

