#!/bin/bash
. "config"

if [[ -z "${1}" ]]; then
  log "ERROR" "Script name required when calling $(basename "$0")"
  exit 3
fi

# If script is already running; abort.
if [[ $(pidof -o %PPID -x "${1}.script") ]]; then
	log "DEBUG" "/usr/local/bin/${1}.script already running. Aborting."
	exit 3
else
  log "DEBUG" "Starting /usr/local/bin/${1}.script"
fi

logfile=${log_dir}/${1}.log
if ([[ "$(printenv USE_LOGFILES)" == "0" ]]); then
  logfile="/proc/1/fd/1"
fi
${1}.script >> ${logfile} 2>&1
