#!/usr/bin/with-contenv bash
. "/usr/local/bin/util"
/bin/s6-svwait -U /var/run/s6/services/read_decrypt
/bin/s6-svwait -U /var/run/s6/services/cloud_decrypt
/bin/s6-svwait -U /var/run/s6/services/local_media
log "INFO" "Starting crond"
crond -f
