#!/usr/bin/with-contenv bash
. "/usr/local/bin/util"
/bin/s6-svwait -U /var/run/s6/services/read_decrypt >/dev/null 2>&1
/bin/s6-svwait -U /var/run/s6/services/cloud_decrypt >/dev/null 2>&1
/bin/s6-svwait -U /var/run/s6/services/local_media >/dev/null 2>&1
info "Starting crond"

crond -f >/dev/null 2>&1 &
PID=${!}
sleep 1
info "Service startup completed"
fdmove -c 2 1 fdmove 1 3 echo >> /dev/null fdmove -c 1 2
wait ${PID}

error "crond terminated, shutting down container"
s6-svscanctl -t /var/run/s6/services >/dev/null 2>&1
exit $?