#!/bin/bash
. "/usr/bin/config"

all_good=1

check_rclone_cloud
check_rclone_local
check_rclone_read

if [ $(ps -ef | grep "rclone" | grep -v "grep" | wc -l) == "0" ]; then
    printf "\n\nRclone is not running\n\n"
    all_good=0
fi

if [ -z "$(ls -A ${cloud_decrypt_dir})" ]; then
    printf "\n\nWaiting for ${cloud_decrypt_dir}\n\n"
    exit 0
fi

if [ -z "$(ls -A ${read_decrypt_dir})" ]; then
    printf "\n\nWaiting for ${read_decrypt_dir}\n\n"
    exit 0
fi

if [ $(ps -ef | grep "unionfs" | grep -v "grep" | wc -l) == "0" ] && [ $(ps -ef | grep "mergerfs" | grep -v "grep" | wc -l) == "0" ]; then
    printf "\n\nUnionFS and MergerFS are not running\n\n"
    all_good=0
fi

if [ "$all_good" -eq "1" ]; then
   printf "\n\nEverything looks good\n\n"
else
    exit 0
fi
