#!/usr/bin/with-contenv bash
. "/usr/local/bin/util"
/bin/s6-svwait -U /var/run/s6/services/read_decrypt >/dev/null 2>&1
info "Starting cloud_decrypt"

precache_complete=0

precache() {
    if [[ "$(printenv RCLONE_PRECACHE)" -eq "1" ]] && [[ "${precache_complete}" -eq "0" ]]; then
        info "Starting VFS pre-cache"
        rclone rc vfs/refresh recursive=true > /dev/null 2>&1
        info "VFS pre-cache complete"
    fi
    precache_complete=1
}

if [[ -z "$(ls -A ${cloud_decrypt_dir})" ]]; then
    info "Mounting cloud_decrypt Google Drive: ${cloud_decrypt_dir}"
    exec rclone mount ${rclone_mount_options} "${cloud_decrypt_endpoint}" "${cloud_decrypt_dir}"&
    PID=${!}
    sleep 1
    precache
    fdmove -c 2 1 fdmove 1 3 echo >> /dev/null fdmove -c 1 2
    wait ${PID}
else
    error "Google Drive cloud_decrypt mountpoint: ${cloud_decrypt_dir} already mounted."
fi

exit $?
