#!/usr/bin/with-contenv bash
. "/usr/local/bin/util"
/bin/s6-svwait -U /var/run/s6/services/read_decrypt
info "Starting cloud_decrypt"

term_handler() {
    info "cloud_decrypt SIGTERM received"
    info "cloud_decrypt unmounting ${cloud_decrypt_dir}"
    s6-svc -t /var/run/s6/services/local_media
    rclone_unmount ${cloud_decrypt_dir}
    info "cloud_decrypt sending SIGTERM to child pid"
    s6-svc -t /var/run/s6/services/read_decrypt
    kill -SIGTERM ${PID} >/dev/null 2>&1
    info "cloud_decrypt exiting"
    exit $?
}

precache() {
    if ([[ "$(printenv RCLONE_PRECACHE)" == "1" ]]); then
        info "Starting VFS pre-cache"
        rclone rc vfs/refresh recursive=true > /dev/null 2>&1
        info "VFS pre-cache complete"
    fi
}

trap term_handler SIGTERM

if [[ -z "$(ls -A ${cloud_decrypt_dir})" ]]; then
    info "Mounting cloud_decrypt Google Drive: ${cloud_decrypt_dir}"
    exec rclone mount ${rclone_mount_options} "${cloud_decrypt_endpoint}" "${cloud_decrypt_dir}"&
    PID=${!}
    sleep 1
    precache
    fdmove -c 2 1 fdmove 1 3 echo >> /dev/null fdmove -c 1 2
    wait ${PID}
else
    error "Google Drive cloud_decrypt mountpoint: ${cloud_decrypt_dir} already mounted."
fi

error "cloud_decrypt script error"
info "cloud_decrypt unmounting ${read_decrypt_dir}"
s6-svc -t /var/run/s6/services/local_media
rclone_unmount ${cloud_decrypt_dir}
s6-svc -t /var/run/s6/services/read_decrypt
info "cloud_decrypt exiting"
exit $?
