#!/usr/bin/with-contenv bash
. "/usr/local/bin/util"

ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

check_read_decrypt

check_cloud_decrypt

#if [[ -d "${secrets_dir}" ]]; then
#    cp ${secrets_dir}/* /config/
#fi

if [[ ! -f "${rclone_exclude_file}" ]]; then
    touch ${rclone_exclude_file}
fi

if [[ ! -d "${local_decrypt_dir}" ]]; then
    mkdir -p "${local_decrypt_dir}"
    chown ${PUID}:${PGID} ${local_decrypt_dir}
fi

if [[ ! -d "${read_decrypt_dir}" ]]; then
    mkdir -p "${read_decrypt_dir}"
    chown ${PUID}:${PGID} ${read_decrypt_dir}
fi

if [[ ! -d "${cloud_decrypt_dir}" ]]; then
    mkdir -p "${cloud_decrypt_dir}"
    chown ${PUID}:${PGID} ${cloud_decrypt_dir}
fi

if [[ ! -d "${local_media_dir}" ]]; then
    mkdir -p "${local_media_dir}"
    chown ${PUID}:${PGID} ${local_media_dir}
fi

chmod -R 777 \
 /var/lock

chown -R $(printenv USER_NAME):$(printenv USER_NAME) \
 /usr/local/bin/*